### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by iNotDev** [kernel-picnic/vkparser#2]
Хотелось бы увидеть "стоп-список", чтобы посты фильтровались без рекламы, потому что в данный момент доля рекламы все же есть. 

Принцип работы:
- скрипт ищет пост.
- если натыкается на пост со словами из "стоп-списка" он считает этот пост рекламой и ищет другой пост.

**Comment by kernel-picnic** [comment]
Да, можно реализовать

**Comment by kernel-picnic** [comment]
Сделал https://github.com/kernel-picnic/vkparser/commit/d8aabe497b208b23592a9976338e21e9debed5d5
