### ISSUE TITLE
помогите запустить

### ISSUE THREAD

**Issue by udmteh** [kernel-picnic/vkparser#4]
сервер выдает ошибку Fatal error: Uncaught Exception: Unable to open database: unable to open database file in /home/d/d95082ke/11/public_html/parser.class.php:66 Stack trace: #0 /home/d/d95082ke/11/public_html/parser.class.php(66): SQLite3->__construct('/home/d/d95082k...') #1 /home/d/d95082ke/11/public_html/parser.class.php(446): VKparser->__construct() #2 {main} thrown in /home/d/d95082ke/11/public_html/parser.class.php on line 66
в чем может быть проблема

**Comment by udmteh** [comment]
Все разобрался спасибо, но почему то бесконечно грузит и ошибка 504, в логах пишет пост не найден хотя паблик популярный

**Comment by udmteh** [comment]
все разобрался, это бесплатный хостер тормозил.
А возможно ли добавить замену хештегов на свои?

**Comment by kernel-picnic** [comment]
> все разобрался, это бесплатный хостер тормозил.
> А возможно ли добавить замену хештегов на свои?

Как вариант могу добавить список фраз, которые нужно заменить в тексте поста

**Comment by udmteh** [comment]
> > все разобрался, это бесплатный хостер тормозил.
> > А возможно ли добавить замену хештегов на свои?
> 
> Как вариант могу добавить список фраз, которые нужно заменить в тексте поста
было бы здорово, и еще добавить функцию что бы можно было добавить свой текст в пост (фразу, сообщение, хештег.) одно и тоже чтобы в каждый пост добавлялось по потребности с указанием ее в config. Спасибо!

**Comment by udmteh** [comment]
обнаружил такую ситуацию, когда скрипт работает на кроне с интервалом в 1 час по стандартным настройкам и указана 1 группа донор то в случае если нет новых постов скрипт через встроенное приложение постоянно посылает запросы на новый пост за вычетом тех что уже были скопированы. в результате отсутствия нового контента и частых запросов вк блокирует приложение (не банит) возрастает тут же нагрузка на хостинг. на аккаунте не работает не одна лента, ни в своей группе ни в любой другой, разморозка наступает рандомно, но более чем через 5 часов, было и сутки, если отключить скрипт в кроне, то разморозка происходит быстрее. (обращаю внимание что если сидеть в вк с компьютера то лента грузится, а с телефона нет!)

**Comment by iNotDev** [comment]
> 
> 
> обнаружил такую ситуацию, когда скрипт работает на кроне с интервалом в 1 час по стандартным настройкам и указана 1 группа донор то в случае если нет новых постов скрипт через встроенное приложение постоянно посылает запросы на новый пост за вычетом тех что уже были скопированы. в результате отсутствия нового контента и частых запросов вк блокирует приложение (не банит) возрастает тут же нагрузка на хостинг. на аккаунте не работает не одна лента, ни в своей группе ни в любой другой, разморозка наступает рандомно, но более чем через 5 часов, было и сутки, если отключить скрипт в кроне, то разморозка происходит быстрее. (обращаю внимание что если сидеть в вк с компьютера то лента грузится, а с телефона нет!)

тоже это заметил, видимо автор забросил скрипт(

**Comment by kernel-picnic** [comment]
> > обнаружил такую ситуацию, когда скрипт работает на кроне с интервалом в 1 час по стандартным настройкам и указана 1 группа донор то в случае если нет новых постов скрипт через встроенное приложение постоянно посылает запросы на новый пост за вычетом тех что уже были скопированы. в результате отсутствия нового контента и частых запросов вк блокирует приложение (не банит) возрастает тут же нагрузка на хостинг. на аккаунте не работает не одна лента, ни в своей группе ни в любой другой, разморозка наступает рандомно, но более чем через 5 часов, было и сутки, если отключить скрипт в кроне, то разморозка происходит быстрее. (обращаю внимание что если сидеть в вк с компьютера то лента грузится, а с телефона нет!)
> 
> тоже это заметил, видимо автор забросил скрипт(

Сейчас не могу много уделять времени скрипту, поэтому так редко вношу изменения

**Comment by kernel-picnic** [comment]
> обнаружил такую ситуацию, когда скрипт работает на кроне с интервалом в 1 час по стандартным настройкам и указана 1 группа донор то в случае если нет новых постов скрипт через встроенное приложение постоянно посылает запросы на новый пост за вычетом тех что уже были скопированы. в результате отсутствия нового контента и частых запросов вк блокирует приложение (не банит) возрастает тут же нагрузка на хостинг. на аккаунте не работает не одна лента, ни в своей группе ни в любой другой, разморозка наступает рандомно, но более чем через 5 часов, было и сутки, если отключить скрипт в кроне, то разморозка происходит быстрее. (обращаю внимание что если сидеть в вк с компьютера то лента грузится, а с телефона нет!)

Могу, как вариант, добавить опцию, которая будет отключать поиск поста "до победного". То есть если мы проверили донора и не нашли ничего, то не возобновлять поиск, а прекратить выполнение. Или есть вариант лучше?

**Comment by iNotDev** [comment]
> Могу, как вариант, добавить опцию, которая будет отключать поиск поста "до победного". То есть если мы проверили донора и не нашли ничего, то не возобновлять поиск, а прекратить выполнение. Или есть вариант лучше?

Да, желательно бы, чтобы он не сыпал ошибку, чтобы не банило приложение.

ибо сейчас получается вот так
[09-Oct-2019 15:31:57 Europe/Moscow] PHP Notice:  Trying to get property of non-object in /parser.class.php on line 102
[09-Oct-2019 15:32:00 Europe/Moscow] PHP Notice:  Undefined property: stdClass::$response in /parser.class.php on line 102

Возможно ли вообще как то расширить диапазон поиска постов?

**Comment by kernel-picnic** [comment]
Могу добавить 2 опции. Одну для того, чтобы поиск прекращался после неудачной попытки. И вторую для задания диапазона поиска. Сейчас парсер смотрит последние 5 записей

**Comment by iNotDev** [comment]
> Могу добавить 2 опции. Одну для того, чтобы поиск прекращался после неудачной попытки. И вторую для задания диапазона поиска. Сейчас парсер смотрит последние 5 записей

А, это я видел в коде, исправил rand (1, 5) на (1, 500).
но даже при этом ошибка, о которой писал выше повторяется.

**Comment by kernel-picnic** [comment]
Добавил опции `SEARCH_RANGE_START`, `SEARCH_RANGE_END` - для указания диапазона поиска

А также `STOP_SEARCH_AFTER_FAILURE` - чтобы парсер останавливал поиск после неудачной попытки

**Comment by kernel-picnic** [comment]
Это обсуждение закрою, потому что тема обсуждений давно ушла от изначальной. Если будут ещё вопросы - создавайте новые issue.
