### ISSUE TITLE
Добавление источника

### ISSUE THREAD

**Issue by iNotDev** [kernel-picnic/vkparser#5]
В ВК после добавления немезиды появилась функция добавить источник на группу, откуда был взят пост. Можно ли реализовать функцию, чтобы пост постился с указанием источника?

Само окно можно найти, когда добавляешь новы пост. Нужно нажать на шестерню и там будет кнопка "добавить источник". Либо же сделать так, 

(тут например текст поста).

Источник: vk.com/wall-123-456
(тут прикрепление)

**Comment by kernel-picnic** [comment]
Добавил опцию в настройки - ADD_COPYRIGHT. Если она включена, то добавляемым постам указывается источник
